-- begin ORDLSSN_ORDER
alter table ORDLSSN_ORDER add constraint FK_ORDLSSN_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references ORDLSSN_CUSTOMER(ID)^
create index IDX_ORDLSSN_ORDER_CUSTOMER on ORDLSSN_ORDER (CUSTOMER_ID)^
-- end ORDLSSN_ORDER
